const express = require('express');
const router = express.Router();
const { ObjectId } = require('mongodb');
const PDFDocument = require('pdfkit');
const nodemailer = require('nodemailer');
const multer = require('multer');
const { connectDB } = require('../config/db');
const { sendReminderMail } = require('../utils/emailHelper');

const upload = multer({ storage: multer.memoryStorage() });

const generateGenieInvoicePDF = (data, doc) => {
    // --- 🎨 PDF CONFIGURATION ---
    const primaryColor = '#4177BC';
    const secondaryColor = '#0F172A';
    const textColor = '#1E293B';
    const lightGray = '#F8FAFC';
    const borderColor = '#E2E8F0';

    // --- 🏢 HEADER & BRANDING ---
    // Brand Logo/Name
    doc.fillColor(primaryColor).fontSize(24).font('Helvetica-Bold').text('GENIE HACK', 50, 45);
    doc.fontSize(9).font('Helvetica').fillColor('#64748B').text('Cyber Security & Digital Solutions', 50, 72);

    // Invoice Label & Details (Right Aligned)
    doc.fillColor(primaryColor).fontSize(28).font('Helvetica-Bold').text('INVOICE', 400, 40, { align: 'right' });
    doc.fontSize(10).fillColor(secondaryColor).font('Helvetica-Bold').text(`Invoice ID: #${data.invoiceId}`, 400, 75, { align: 'right' });
    doc.font('Helvetica').fillColor('#64748B').text(`Date: ${new Date(data.createdAt || Date.now()).toLocaleDateString('en-GB')}`, 400, 90, { align: 'right' });

    // Top Divider Line
    doc.moveTo(50, 115).lineTo(545, 115).lineWidth(1.5).strokeColor(primaryColor).stroke();

    // --- 👥 BILLING INFORMATION ---
    const topOfInfo = 135;

    // From Section
    doc.fillColor(primaryColor).fontSize(9).font('Helvetica-Bold').text('FROM:', 50, topOfInfo);
    doc.fillColor(secondaryColor).fontSize(11).text('Genie Hack Ltd.', 50, topOfInfo + 15);
    doc.fontSize(9).font('Helvetica').fillColor('#64748B').text('Dhaka, Bangladesh', 50, topOfInfo + 30);
    doc.text('support@geniehack.com', 50, topOfInfo + 42);

    // Bill To Section
    doc.fillColor(primaryColor).fontSize(9).font('Helvetica-Bold').text('BILL TO:', 350, topOfInfo);
    doc.fillColor(secondaryColor).fontSize(11).text(data.clientName || 'Valued Client', 350, topOfInfo + 15);
    doc.fontSize(9).font('Helvetica').fillColor('#64748B').text(data.clientEmail || '', 350, topOfInfo + 30);
    doc.text(`Project: ${data.projectTitle || 'N/A'}`, 350, topOfInfo + 42);

    // --- 📊 MILESTONE ITEMS TABLE ---
    const tableTop = 230;

    // Header Background
    doc.rect(50, tableTop, 500, 25).fill(primaryColor);

    // Header Text
    doc.fillColor('#FFFFFF').fontSize(10).font('Helvetica-Bold');
    doc.text('Milestone Description', 60, tableTop + 8);
    doc.text('Due Date', 280, tableTop + 8);
    doc.text('Status', 380, tableTop + 8);
    doc.text('Amount', 480, tableTop + 8);

    let i = 0;
    // data.milestonesSnapshot থেকে ডাটা নিয়ে লুপ ঘুরবে
    const items = data.milestonesSnapshot || [{ name: data.projectTitle, amount: data.grandTotal, status: data.status, dueDate: null }];

    items.forEach((item, index) => {
        const y = tableTop + 25 + (index * 25);

        // Alternate Row Background
        if (index % 2 === 0) doc.rect(50, y, 500, 25).fill(lightGray);

        doc.fillColor(textColor).fontSize(9).font('Helvetica');

        // Description
        doc.text(item.name || 'Service Component', 60, y + 8, { width: 210, lineBreak: false });

        // Due Date
        doc.text(item.dueDate ? new Date(item.dueDate).toLocaleDateString('en-GB') : '---', 280, y + 8);

        // Status with Color Coding
        const isPaid = item.status?.toLowerCase() === 'paid';
        doc.fillColor(isPaid ? '#10B981' : '#F59E0B').font('Helvetica-Bold');
        doc.text(item.status ? item.status.toUpperCase() : 'PENDING', 380, y + 8);

        // Amount
        doc.fillColor(secondaryColor).font('Helvetica');
        doc.text(`${data.currency || '$'} ${Number(item.amount || 0).toLocaleString()}`, 480, y + 8);

        i++;
    });

    // --- 💰 TOTALS SECTION ---
    const subtotalY = tableTop + 25 + (i * 25) + 30;

    // Grand Total Box
    doc.rect(345, subtotalY, 205, 40).fill(primaryColor);
    doc.fillColor('#FFFFFF').fontSize(12).font('Helvetica-Bold').text('AMOUNT PAID', 355, subtotalY + 14);
    doc.fontSize(14).text(`${data.currency || '$'} ${Number(data.grandTotal).toLocaleString()}`, 450, subtotalY + 13, { align: 'right', width: 90 });

    // Payment Method Information
    doc.fillColor(secondaryColor).fontSize(9).font('Helvetica-Bold').text('Payment Method:', 50, subtotalY);
    doc.font('Helvetica').fillColor('#64748B').text(data.paymentMethod || 'Manual Transaction', 50, subtotalY + 15);

    // --- 📝 FOOTER ---
    const footerTop = 750;
    doc.moveTo(50, footerTop).lineTo(545, footerTop).lineWidth(0.5).strokeColor(borderColor).stroke();

    doc.fontSize(8).fillColor('#94A3B8').text('This is an automated invoice generated by Genie Hack Ltd.', 50, footerTop + 15, { align: 'center', width: 500 });
    doc.text('Thank you for your business!', 50, footerTop + 27, { align: 'center', width: 500 });

    // Finalize PDF
    doc.end();
};



/** 1️⃣ GET INVOICES (Master Fetch: Admin sees all, Client sees only theirs) **/
router.get('/', async (req, res) => {
    try {
        const { search, status, email, clientEmail, role } = req.query;

        // ✅ কানেকশন এখানে নিয়ে আসুন (ফাংশনের ভেতরে)
        const database = await connectDB();
        const collection = database.collection("invoices");

        let query = {};

        // --- 🛡️ ACCESS CONTROL LOGIC ---
        if (role === 'admin') {
            query = {};
        } else {
            const targetEmail = (email || clientEmail)?.toLowerCase().trim();
            if (!targetEmail) {
                return res.status(400).send({ error: "Client email is required to fetch records" });
            }
            query = { clientEmail: targetEmail };
        }

        // --- 🔍 SEARCH LOGIC ---
        if (search) {
            query.$and = [
                { ...query },
                {
                    $or: [
                        { invoiceId: { $regex: search, $options: 'i' } },
                        { clientName: { $regex: search, $options: 'i' } },
                        { projectTitle: { $regex: search, $options: 'i' } },
                        { clientEmail: { $regex: search, $options: 'i' } }
                    ]
                }
            ];
        }

        // --- 🏷️ STATUS FILTER ---
        if (status && status !== 'All') {
            query.status = status;
        }

        // --- 🚀 DATABASE EXECUTION ---
        const invoices = await collection
            .find(query)
            .sort({ createdAt: -1 })
            .toArray();

        res.status(200).send(invoices);

    } catch (err) {
        console.error("Critical Invoice Fetch Error:", err);
        res.status(500).send({ error: "Internal Server Error while fetching ledger" });
    }
});

/** 2️⃣ CREATE INVOICE (With Global Dashboard Sync) **/
router.post('/', async (req, res) => {
    try {
        const database = await connectDB();
        const invoiceCollection = database.collection("invoices");
        const usersCollection = database.collection("users");

        // সংশোধন: req.body থেকে ডাটা বের করে নিন
        const { adminEmail, clientEmail, projectId, milestone, project, paymentMethod } = req.body;

        const invoiceData = {
            invoiceId: `INV-${Date.now().toString().slice(-6)}`,
            projectId: projectId,
            milestoneId: milestone._id || `M-${milestoneIndex}`,
            projectTitle: project.name,
            clientName: client.name,
            clientEmail: client.email.toLowerCase().trim(),

            grandTotal: Number(milestone.amount),
            remainingDue: 0,
            receivedAmount: Number(milestone.amount),

            amount: Number(milestone.amount),
            method: paymentMethod || "Online Payment",
            status: "Paid",
            paymentDate: new Date(),
            milestonesSnapshot: project.milestones,
            createdAt: new Date()
        };

        const result = await invoiceCollection.insertOne(invoiceData);
        const summaryData = {
            _id: result.insertedId,
            invoiceId: invoiceData.invoiceId,
            projectTitle: invoiceData.projectTitle,
            clientName: invoiceData.clientName,
            grandTotal: invoiceData.grandTotal,
            status: invoiceData.status,
            date: invoiceData.createdAt
        };

        await usersCollection.updateOne({ email: invoiceData.adminEmail }, { $push: { myCreatedInvoices: summaryData } });
        await usersCollection.updateOne({ email: invoiceData.clientEmail }, { $push: { invoicesReceived: summaryData } });

        res.status(201).send({ message: "✅ Invoice created & synced", id: result.insertedId });
    } catch (err) { res.status(500).send({ error: "Failed to create invoice" }); }
});

/** 3️⃣ GET SINGLE INVOICE **/
router.get('/:id', async (req, res) => {
    try {
        const database = await connectDB();
        const query = ObjectId.isValid(req.params.id) ? { _id: new ObjectId(req.params.id) } : { invoiceId: req.params.id };
        const inv = await database.collection("invoices").findOne(query);
        inv ? res.send(inv) : res.status(404).send({ error: "Not found" });
    } catch (err) { res.status(500).send({ error: "Internal error" }); }
});

/** 4️⃣ SEND EMAIL (Fixed Professional PDF Attachment) **/
router.post('/send-email', async (req, res) => {
    try {
        const database = await connectDB();
        const invColl = database.collection("invoices");
        const userColl = database.collection("users");
        const settingsColl = database.collection("settings");
        const inv = req.body;

        if (!inv.clientEmail) return res.status(400).json({ error: "Client email is missing" });

        // PayPal Link Logic
        const siteSettings = await settingsColl.findOne({});
        const userProvidedLink = siteSettings?.paypalLink || inv.paypalEmail || process.env.PAYPAL_EMAIL || "";
        let finalPaymentLink = userProvidedLink;
        if (userProvidedLink.includes('@')) {
            finalPaymentLink = `https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=${userProvidedLink}&amount=${inv.remainingDue}&currency_code=${inv.currency}&item_name=Invoice_${inv.invoiceId}`;
        }

        // PDF Generation via Buffers (Fixes dest.write error)
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        let buffers = [];
        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', async () => {
            const pdfBuffer = Buffer.concat(buffers);
            const transporter = nodemailer.createTransport({
                service: 'gmail',
                auth: { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS }
            });

            await transporter.sendMail({
                from: `"Genie Hack Billing" <${process.env.EMAIL_USER}>`,
                to: inv.clientEmail,
                subject: `Invoice #${inv.invoiceId} from Genie Hack`,
                html: `<div style="font-family: sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; padding: 30px; border-radius: 15px;">
                        <h2 style="color: #4177BC; text-align: center;">Genie Hack Billing</h2>
                        <p>Hello <b>${inv.clientName}</b>,</p>
                        <p>Your invoice <b>#${inv.invoiceId}</b> is ready.</p>
                        <div style="background: #f8fafc; padding: 20px; border-radius: 10px;">
                            <p>Total Amount: <b>${inv.currency} ${inv.grandTotal}</b></p>
                            <p>Status: <span style="color: #f59e0b;">${inv.status}</span></p>
                        </div>
                        <div style="text-align: center; margin: 30px 0;">
                            <a href="${finalPaymentLink}" style="background:#4177BC; color:white; padding:15px 30px; text-decoration:none; border-radius:8px; font-weight: bold;">Pay via PayPal</a>
                        </div>
                        <p style="font-size: 12px; color: #999;">Find the official PDF attached.</p>
                      </div>`,
                attachments: [{ filename: `Invoice_${inv.invoiceId}.pdf`, content: pdfBuffer }]
            });

            // Global Sync
            await invColl.updateOne({ invoiceId: inv.invoiceId }, { $set: { status: "Sent", updatedAt: new Date() } });
            await userColl.updateOne({ email: inv.adminEmail, "myCreatedInvoices.invoiceId": inv.invoiceId }, { $set: { "myCreatedInvoices.$.status": "Sent" } });
            await userColl.updateOne({ email: inv.clientEmail, "invoicesReceived.invoiceId": inv.invoiceId }, { $set: { "invoicesReceived.$.status": "Sent" } });

            res.status(200).json({ success: true, message: "✅ Email Sent and Database Synced!" });
        });

        generateGenieInvoicePDF(inv, doc);
    } catch (err) { res.status(500).json({ error: "Master Error during email processing" }); }
});

/** 5️⃣ DOWNLOAD PDF **/
router.get('/:id/download', async (req, res) => {
    try {
        const database = await connectDB();
        const query = ObjectId.isValid(req.params.id) ? { _id: new ObjectId(req.params.id) } : { invoiceId: req.params.id };
        const inv = await database.collection("invoices").findOne(query);
        if (!inv) return res.status(404).send({ error: "Invoice not found" });

        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=Invoice-${inv.invoiceId}.pdf`);

        doc.pipe(res);
        generateGenieInvoicePDF(inv, doc);
    } catch (err) { res.status(500).send({ error: "PDF Generation error" }); }
});

/** 6️⃣ PATCH (Global Update) **/
router.patch('/:id', async (req, res) => {
    try {
        const database = await connectDB();
        const invoiceColl = database.collection("invoices");
        const userColl = database.collection("users");
        const invoiceObjectId = ObjectId.isValid(req.params.id) ? new ObjectId(req.params.id) : null;
        const { _id, createdAt, ...updateFields } = req.body;

        await invoiceColl.updateOne({ _id: invoiceObjectId }, { $set: { ...updateFields, updatedAt: new Date() } });
        const updated = await invoiceColl.findOne({ _id: invoiceObjectId });
        if (updated) {
            await userColl.updateOne({ email: updated.adminEmail, "myCreatedInvoices._id": updated._id }, { $set: { "myCreatedInvoices.$.status": updated.status, "myCreatedInvoices.$.grandTotal": updated.grandTotal, "myCreatedInvoices.$.projectTitle": updated.projectTitle } });
            await userColl.updateOne({ email: updated.clientEmail, "invoicesReceived._id": updated._id }, { $set: { "invoicesReceived.$.status": updated.status, "invoicesReceived.$.grandTotal": updated.grandTotal } });
        }
        res.send({ message: "✅ Global update successful" });
    } catch (err) { res.status(500).send({ error: "Update failed" }); }
});

/** 7️⃣ DELETE (Global Cleanup) **/
router.delete('/:id', async (req, res) => {
    try {
        const database = await connectDB();
        const query = ObjectId.isValid(req.params.id) ? { _id: new ObjectId(req.params.id) } : { invoiceId: req.params.id };
        const inv = await database.collection("invoices").findOne(query);
        if (inv) {
            await database.collection("users").updateOne({ email: inv.adminEmail }, { $pull: { myCreatedInvoices: { _id: inv._id } } });
            await database.collection("users").updateOne({ email: inv.clientEmail }, { $pull: { invoicesReceived: { _id: inv._id } } });
            await database.collection("invoices").deleteOne({ _id: inv._id });
        }
        res.send({ message: "🗑️ Deleted globally" });
    } catch (err) { res.status(500).send({ error: "Delete failed" }); }
});

/** 8️⃣ BULK DELETE **/
router.post('/bulk-delete', async (req, res) => {
    try {
        const { ids } = req.body;
        const database = await connectDB();
        const invoiceColl = database.collection("invoices");
        const userColl = database.collection("users");
        const objectIds = ids.map(id => new ObjectId(id));
        const invoicesToDelete = await invoiceColl.find({ _id: { $in: objectIds } }).toArray();

        for (const inv of invoicesToDelete) {
            await userColl.updateOne({ email: inv.adminEmail }, { $pull: { myCreatedInvoices: { _id: inv._id } } });
            await userColl.updateOne({ email: inv.clientEmail }, { $pull: { invoicesReceived: { _id: inv._id } } });
        }
        await invoiceColl.deleteMany({ _id: { $in: objectIds } });
        res.status(200).send({ message: "🗑️ Bulk deleted globally" });
    } catch (err) { res.status(500).send({ error: "Bulk delete failed" }); }
});

/** 🔄 UPDATE STATUS & MILESTONE AUTO-SYNC (Typo Fix: clinets -> clients) **/
router.put('/update-status/:invoiceId', async (req, res) => {
    try {
        const { status } = req.body;
        const database = await connectDB();
        const invoiceColl = database.collection("invoices");
        const clientColl = database.collection("clients"); // Fixed typo
        const userColl = database.collection("users");

        const currentInvoice = await invoiceColl.findOneAndUpdate(
            { invoiceId: req.params.invoiceId },
            { $set: { status: status, updatedAt: new Date() } },
            { returnDocument: 'after' }
        );

        if (!currentInvoice) return res.status(404).send({ error: "Invoice not found" });

        await userColl.updateOne({ email: currentInvoice.adminEmail, "myCreatedInvoices.invoiceId": currentInvoice.invoiceId }, { $set: { "myCreatedInvoices.$.status": status } });
        await userColl.updateOne({ email: currentInvoice.clientEmail, "invoicesReceived.invoiceId": currentInvoice.invoiceId }, { $set: { "invoicesReceived.$.status": status } });

        if (status === "Paid" && currentInvoice.projectId) {
            const projId = new ObjectId(currentInvoice.projectId);
            const client = await clientColl.findOne({ "projects._id": projId });
            const project = client?.projects.find(p => p._id.toString() === projId.toString());

            if (project) {
                const alreadyPaid = Number(project.paidAmount || 0) + Number(currentInvoice.grandTotal || 0);
                const nextStep = (project.currentStep || 1) + 1;
                const nextMilestone = project.milestones[nextStep - 1];

                if (nextMilestone) {
                    const nextInvoiceData = {
                        invoiceId: `INV-${Date.now().toString().slice(-6)}`,
                        projectId: project._id,
                        projectTitle: project.name,
                        clientName: client.name,
                        clientEmail: client.email.toLowerCase(),
                        adminEmail: currentInvoice.adminEmail.toLowerCase(),
                        grandTotal: Number(nextMilestone.amount),
                        currency: currentInvoice.currency || "$",
                        status: "Unpaid",
                        createdAt: new Date()
                    };
                    const savedNext = await invoiceColl.insertOne(nextInvoiceData);
                    const summary = { _id: savedNext.insertedId, invoiceId: nextInvoiceData.invoiceId, projectTitle: nextInvoiceData.projectTitle, clientName: nextInvoiceData.clientName, grandTotal: nextInvoiceData.grandTotal, status: "Unpaid", date: new Date() };

                    await userColl.updateOne({ email: nextInvoiceData.adminEmail }, { $push: { myCreatedInvoices: summary } });
                    await userColl.updateOne({ email: nextInvoiceData.clientEmail }, { $push: { invoicesReceived: summary } });
                    await clientColl.updateOne({ "projects._id": project._id }, { $set: { "projects.$.currentStep": nextStep, "projects.$.paidAmount": alreadyPaid } });
                } else {
                    await clientColl.updateOne({ "projects._id": project._id }, { $set: { "projects.$.status": "Completed", "projects.$.progress": 100, "projects.$.paidAmount": alreadyPaid } });
                }
            }
        }
        res.json({ success: true, message: "System Synced Successfully!" });
    } catch (err) { res.status(500).json({ error: "Sync failed" }); }
});

/** 💳 PROCESS FINAL PAYMENT **/
router.post('/process-final-payment', async (req, res) => {
    try {
        const { clientId, projectId, milestoneId, invoiceId, paymentAmount } = req.body;
        const database = await connectDB();
        const invoiceColl = database.collection("invoices");

        await invoiceColl.findOneAndUpdate(
            { invoiceId: invoiceId },
            { $set: { status: 'Paid', receivedAmount: paymentAmount, remainingDue: 0, updatedAt: new Date() } }
        );

        await database.collection("clients").updateOne( // Fixed typo
            { _id: new ObjectId(clientId) },
            {
                $set: { "projects.$[proj].milestones.$[mile].status": "Paid", "projects.$[proj].milestones.$[mile].isCompleted": true },
                $inc: { totalPaid: Number(paymentAmount) }
            },
            { arrayFilters: [{ "proj._id": new ObjectId(projectId) }, { "mile._id": new ObjectId(milestoneId) }] }
        );

        res.json({ success: true, message: "Final Payment Processed Successfully!" });
    } catch (err) { res.status(500).json({ error: "Final integration failed" }); }
});

/** 9️⃣ DOWNLOAD PDF (Improved & Integrated) **/
router.get('/download/:id', async (req, res) => {
    try {
        const { id } = req.params;
        const database = await connectDB();
        const collection = database.collection("invoices");

        const query = ObjectId.isValid(id) ? { _id: new ObjectId(id) } : { invoiceId: id };
        const inv = await collection.findOne(query);

        if (!inv) return res.status(404).send({ error: "Invoice not found" });

        // PDF Response Headers
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=Invoice-${inv.invoiceId}.pdf`);

        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        doc.pipe(res);

        generateGenieInvoicePDF(inv, doc);

    } catch (err) {
        console.error("PDF Download Error:", err);
        res.status(500).send("Failed to generate PDF");
    }
});

module.exports = { router, generateGenieInvoicePDF }; 